require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ContractorsController do

  # This should return the minimal set of attributes required to create a valid
  # Contractor. As you add validations to Contractor, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all contractors as @contractors" do
      contractor = Contractor.create! valid_attributes
      get :index
      assigns(:contractors).should eq([contractor])
    end
  end

  describe "GET show" do
    it "assigns the requested contractor as @contractor" do
      contractor = Contractor.create! valid_attributes
      get :show, :id => contractor.id.to_s
      assigns(:contractor).should eq(contractor)
    end
  end

  describe "GET new" do
    it "assigns a new contractor as @contractor" do
      get :new
      assigns(:contractor).should be_a_new(Contractor)
    end
  end

  describe "GET edit" do
    it "assigns the requested contractor as @contractor" do
      contractor = Contractor.create! valid_attributes
      get :edit, :id => contractor.id.to_s
      assigns(:contractor).should eq(contractor)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Contractor" do
        expect {
          post :create, :contractor => valid_attributes
        }.to change(Contractor, :count).by(1)
      end

      it "assigns a newly created contractor as @contractor" do
        post :create, :contractor => valid_attributes
        assigns(:contractor).should be_a(Contractor)
        assigns(:contractor).should be_persisted
      end

      it "redirects to the created contractor" do
        post :create, :contractor => valid_attributes
        response.should redirect_to(Contractor.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved contractor as @contractor" do
        # Trigger the behavior that occurs when invalid params are submitted
        Contractor.any_instance.stub(:save).and_return(false)
        post :create, :contractor => {}
        assigns(:contractor).should be_a_new(Contractor)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Contractor.any_instance.stub(:save).and_return(false)
        post :create, :contractor => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested contractor" do
        contractor = Contractor.create! valid_attributes
        # Assuming there are no other contractors in the database, this
        # specifies that the Contractor created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Contractor.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => contractor.id, :contractor => {'these' => 'params'}
      end

      it "assigns the requested contractor as @contractor" do
        contractor = Contractor.create! valid_attributes
        put :update, :id => contractor.id, :contractor => valid_attributes
        assigns(:contractor).should eq(contractor)
      end

      it "redirects to the contractor" do
        contractor = Contractor.create! valid_attributes
        put :update, :id => contractor.id, :contractor => valid_attributes
        response.should redirect_to(contractor)
      end
    end

    describe "with invalid params" do
      it "assigns the contractor as @contractor" do
        contractor = Contractor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Contractor.any_instance.stub(:save).and_return(false)
        put :update, :id => contractor.id.to_s, :contractor => {}
        assigns(:contractor).should eq(contractor)
      end

      it "re-renders the 'edit' template" do
        contractor = Contractor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Contractor.any_instance.stub(:save).and_return(false)
        put :update, :id => contractor.id.to_s, :contractor => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested contractor" do
      contractor = Contractor.create! valid_attributes
      expect {
        delete :destroy, :id => contractor.id.to_s
      }.to change(Contractor, :count).by(-1)
    end

    it "redirects to the contractors list" do
      contractor = Contractor.create! valid_attributes
      delete :destroy, :id => contractor.id.to_s
      response.should redirect_to(contractors_url)
    end
  end

end
