require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe KeyPeopleController do

  # This should return the minimal set of attributes required to create a valid
  # KeyPerson. As you add validations to KeyPerson, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all key_people as @key_people" do
      key_person = KeyPerson.create! valid_attributes
      get :index
      assigns(:key_people).should eq([key_person])
    end
  end

  describe "GET show" do
    it "assigns the requested key_person as @key_person" do
      key_person = KeyPerson.create! valid_attributes
      get :show, :id => key_person.id.to_s
      assigns(:key_person).should eq(key_person)
    end
  end

  describe "GET new" do
    it "assigns a new key_person as @key_person" do
      get :new
      assigns(:key_person).should be_a_new(KeyPerson)
    end
  end

  describe "GET edit" do
    it "assigns the requested key_person as @key_person" do
      key_person = KeyPerson.create! valid_attributes
      get :edit, :id => key_person.id.to_s
      assigns(:key_person).should eq(key_person)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new KeyPerson" do
        expect {
          post :create, :key_person => valid_attributes
        }.to change(KeyPerson, :count).by(1)
      end

      it "assigns a newly created key_person as @key_person" do
        post :create, :key_person => valid_attributes
        assigns(:key_person).should be_a(KeyPerson)
        assigns(:key_person).should be_persisted
      end

      it "redirects to the created key_person" do
        post :create, :key_person => valid_attributes
        response.should redirect_to(KeyPerson.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved key_person as @key_person" do
        # Trigger the behavior that occurs when invalid params are submitted
        KeyPerson.any_instance.stub(:save).and_return(false)
        post :create, :key_person => {}
        assigns(:key_person).should be_a_new(KeyPerson)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        KeyPerson.any_instance.stub(:save).and_return(false)
        post :create, :key_person => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested key_person" do
        key_person = KeyPerson.create! valid_attributes
        # Assuming there are no other key_people in the database, this
        # specifies that the KeyPerson created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        KeyPerson.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => key_person.id, :key_person => {'these' => 'params'}
      end

      it "assigns the requested key_person as @key_person" do
        key_person = KeyPerson.create! valid_attributes
        put :update, :id => key_person.id, :key_person => valid_attributes
        assigns(:key_person).should eq(key_person)
      end

      it "redirects to the key_person" do
        key_person = KeyPerson.create! valid_attributes
        put :update, :id => key_person.id, :key_person => valid_attributes
        response.should redirect_to(key_person)
      end
    end

    describe "with invalid params" do
      it "assigns the key_person as @key_person" do
        key_person = KeyPerson.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        KeyPerson.any_instance.stub(:save).and_return(false)
        put :update, :id => key_person.id.to_s, :key_person => {}
        assigns(:key_person).should eq(key_person)
      end

      it "re-renders the 'edit' template" do
        key_person = KeyPerson.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        KeyPerson.any_instance.stub(:save).and_return(false)
        put :update, :id => key_person.id.to_s, :key_person => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested key_person" do
      key_person = KeyPerson.create! valid_attributes
      expect {
        delete :destroy, :id => key_person.id.to_s
      }.to change(KeyPerson, :count).by(-1)
    end

    it "redirects to the key_people list" do
      key_person = KeyPerson.create! valid_attributes
      delete :destroy, :id => key_person.id.to_s
      response.should redirect_to(key_people_url)
    end
  end

end
